kind: pipeline
type: kubernetes
name: default

steps:
- name: build-and-push-docker-image
  image: plugins/docker
  settings:
    username:
      from_secret: registry_user
    password:
      from_secret: registry_pw
    repo:
      from_secret: registry_repo
    registry:
      from_secret: registry_base_url
    dockerfile: build/Dockerfile
    tags:
      - ${DRONE_TAG}

trigger:
  event:
  - tag
  ref:
  - refs/tags/v*[1-9].*[0-9].*[0-9]-rc.*[0-9]