---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build-and-push-docker-image
  image: plugins/docker
  settings:
    username:
      from_secret: registry_user
    password:
      from_secret: registry_password
    repo: registry.flow.swiss/k8s/csi-driver
    registry: registry.flow.swiss
    dockerfile: build/Dockerfile
    mtu: 1450
    tags:
      - ${DRONE_TAG}

trigger:
  event:
  - tag
  ref:
  - refs/tags/*
---
kind: signature
hmac: f7c6ef93dffeac201cb017e6447d3917a35e9dd19e6cb5453d3c20e6841e34a7

...
